### PR TITLE
Text Area for Missing Words Feature

### PR DESCRIPTION
**Pull request by cofinley**
Separate features into window tabs for future use. 

- First tab is missing words feature. 
  - This includes the text area and search button for that tab.

Also:
- Separate main widget from all other children widgets in views directory
- Clean up Qt inheritance, other OOP inconsistencies

### CODE REVIEW

**Comment by jeprecated** [comment]
Hey, nice stuff 👍 

Alright I guess I need to actually build the project then. Got some tips for that? I know there's the documentation here: https://apps.ankiweb.net/docs/addons.html Is there anything specific your test project needs before I can run it? Into the world of Anki extensions we go!

**Comment by cofinley** [comment]
I’ve included something in the readme for Windows. I have yet to find a
faster way to develop besides reloading Anki each time :/

No building necessary, the repo just needs to be in the addons folder as is
(symlink is easiest for development, as seen in readme).

There is Qt Designer which is like a live preview of Qt stuff, but I’m not
sure if we can take advantage of it. Anki has their own Qt library instance
that is only exposed by running Anki. We could maybe develop the UI portion faster
with a regular Qt library installation (different import statements), then
change the import statement on a build so it will work with Anki’s version.
Not sure how far that’ll take us though.

**Comment by cofinley** [comment]
[This discussion post](https://anki.tenderapp.com/discussions/add-ons/12396-add-on-development-environment-help-needed) gives me some hope. Namely [this addon reloader plugin](https://ankiweb.net/shared/info/348783334) and [this guide](https://chrisk91.me/2018/02/13/Setting-up-VSCode-for-Anki-addon-development.html) (vscode and pycharm discussed).

**Comment by cofinley** [comment]
I also added a dev styleguide type of document to the wiki: https://github.com/ll-in-anki/anki-LL/wiki/Qt---Notes-and-Guidelines

**Comment by jeprecated** [comment]
Looking good so far, can confirm the window looks good 👍 

Though I am having troubles setting up my python environment to get some proper error messages. Some of the requirements are just refusing to install, and stealing away the precious little time I have while on holiday.

I'll have it all sorted by the time I get back in a week! 👍 Good efforts so far, I look forward to helping soon.

Edit: Feel free and merge this in at your own leasure!

**Comment by cofinley** [comment]
Sounds good. I can help out with errors if/when you want. But definitely enjoy your holiday instead of troubleshooting :)

I’ll go ahead and merge then.

**Pull request merged**
