### PR TITLE
Reorg

### PR DESCRIPTION
**Pull request by cofinley**
Move to glutanimate's repo organization style so we can use the addon builder and UI files for easier development.

Easier to test this one out by following the steps in `docs/DEVELOPMENT.md`.

I removed `create_notes.py` for now since we should probably narrow down what we want with a prototype first. I also removed the main tabs since the original thought was that they were going to hold other addons inside a mega-addon.

I also changed the search preview a little:

image
image
image

### CODE REVIEW

**Comment by jeprecated** [comment]
Tried to have a look just now, but I'm getting some build errors.

image

Seems it can't find ".anki21". I built using aab, did I miss anything else? Or could something be missing from the repo?

**Comment by cofinley** [comment]
Lol I added pylintrc specifically so we can have a standard format. See the comment on .gitignore from last PR: https://github.com/ll-in-anki/find-missing-words/pull/4#discussion_r322510362

**Comment by cofinley** [comment]
Did you use our aab fork? I just run ‘aab build’ from the project root. Maybe a pic of your dist/ and addon directories hierarchy would help.

**Comment by jeprecated** [comment]
> Lol I added pylintrc specifically so we can have a standard format. See the comment on .gitignore from last PR: [#4 (comment)](https://github.com/ll-in-anki/find-missing-words/pull/4#discussion_r322510362)

But we cannot have that with this file, as part of the setup for linting is to point to your own specific anki build, as it says in [the guide we followed](https://chrisk91.me/2018/02/13/Setting-up-VSCode-for-Anki-addon-development.html). 

```
[Master]
init-hook='import sys; sys.path.append("X:/.../anki-2.0.47/")'
```

My one will be different than yours.

**Comment by jeprecated** [comment]
> Did you use our aab fork? I just run ‘aab build’ from the project root. Maybe a pic of your dist/ directory hierarchy would help.

I did indeed. Will try again tonight and send you a screenshot 👍

**Comment by cofinley** [comment]
I see what you mean with linting. The imports appear with red lines for me but I know that I can just ignore them. I wonder if the vscode project settings can suffice to fix that. The article talks about that as a part of the fix, but not sure if it could be achieved by doing only that (specifying the python.pythonPath).

**Comment by jeprecated** [comment]
Still can't find what's wrong. Here's a pic of my folder structure.

image

**Comment by cofinley** [comment]
Your project dir looks correct. What’s Anki looking at? The build or the src?

**Comment by jeprecated** [comment]
At the src... Ah. Yes. That makes sense, lol. Will try that again with the build folder tonight 😅

**Comment by jeprecated** [comment]
Working! My bad :sweat_smile: Happy to merge the current version :+1:

**Review by jeprecated — APPROVED** [review]
:+1:

**Pull request merged**
